# Travis configuration file
# http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"

# Installing Dependencies...
install:
  - sudo apt-get update
  - sudo apt-get install libusb-1.0-0-dev
  - pip install -r requirements.txt

# Installing chimera...
script:
  - python setup.py install

